export const invoices = [
  {
    id: 'INV-2024-001',
    vendorName: 'Sai Steel Traders',
    amount: 472000,
    hsnCode: '7209',
    gstRate: 18,
    date: '15-Mar-2025',
    vendorFilingStatus: 'Irregular',
    status: 'pending',
    analysis: null,
  },
  {
    id: 'INV-2024-002',
    vendorName: 'Bharat Polymers Ltd',
    amount: 185000,
    hsnCode: '3917',
    gstRate: 18,
    date: '22-Mar-2025',
    vendorFilingStatus: 'Regular',
    status: 'pending',
    analysis: null,
  },
  {
    id: 'INV-2024-003',
    vendorName: 'Gupta Electrical Supply',
    amount: 630000,
    hsnCode: '8538',
    gstRate: 18,
    date: '01-Apr-2025',
    vendorFilingStatus: 'Irregular',
    status: 'pending',
    analysis: null,
  },
  {
    id: 'INV-2024-004',
    vendorName: 'Laxmi Packaging House',
    amount: 92000,
    hsnCode: '4819',
    gstRate: 12,
    date: '10-Apr-2025',
    vendorFilingStatus: 'Regular',
    status: 'pending',
    analysis: null,
  },
  {
    id: 'INV-2024-005',
    vendorName: 'Om Logistics Partner',
    amount: 315000,
    hsnCode: '9965',
    gstRate: 18,
    date: '18-Apr-2025',
    vendorFilingStatus: 'Defaulter',
    status: 'pending',
    analysis: null,
  },
];

export const vendors = [
  {
    id: 'V001',
    name: 'Sai Steel Traders',
    gstin: '07AABCS****M1Z5',
    reliability: 45,
    filingStatus: 'Irregular',
    invoiceCount: 12,
    riskLevel: 'High',
    riskNote: 'Missed 3 of last 6 GSTR-1 filings',
    analysis: null,
  },
  {
    id: 'V002',
    name: 'Bharat Polymers Ltd',
    gstin: '27AABCB****P1Z3',
    reliability: 92,
    filingStatus: 'Regular',
    invoiceCount: 28,
    riskLevel: 'Low',
    riskNote: 'Consistent filer, no issues',
    analysis: null,
  },
  {
    id: 'V003',
    name: 'Gupta Electrical Supply',
    gstin: '09AABCG****E1Z7',
    reliability: 68,
    filingStatus: 'Irregular',
    invoiceCount: 8,
    riskLevel: 'Medium',
    riskNote: 'Late filings in 2 of last 4 months',
    analysis: null,
  },
  {
    id: 'V004',
    name: 'Om Logistics Partner',
    gstin: '06AABCO****L1Z1',
    reliability: 22,
    filingStatus: 'Defaulter',
    invoiceCount: 5,
    riskLevel: 'Critical',
    riskNote: 'No GSTR-1 filed since Jan 2025',
    analysis: null,
  },
];

export function formatCurrency(num) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(num);
}